version = 3.10.7
runner.dialect = scala3
align.preset = most
maxColumn = 120
newlines.source = keep
lineEndings = preserve
docstrings = JavaDoc
docstrings.wrapMaxColumn = 80
project.git = true
rewrite.rules = [RedundantBraces, RedundantParens, Imports]
rewrite.scala3.removeOptionalBraces = false
rewrite.scala3.convertToNewSyntax = false
