addSbtPlugin("com.eed3si9n"       % "sbt-assembly"  % "2.4.0")
addSbtPlugin("com.timushev.sbt"   % "sbt-updates"   % "0.7.0")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"  % "2.6.2")
addSbtPlugin("org.scoverage"      % "sbt-scoverage" % "2.4.4")
addSbtPlugin("ch.epfl.scala"      % "sbt-bloop"     % "2.1.1")
addSbtPlugin("io.stryker-mutator" % "sbt-stryker4s" % "1.0.3")
