addSbtPlugin("com.eed3si9n"   % "sbt-assembly"           % "2.1.0")
addSbtPlugin("org.jmotor.sbt" % "sbt-dependency-updates" % "1.2.7")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"           % "2.5.0")
addSbtPlugin("org.scoverage"  % "sbt-coveralls"          % "1.3.6")
addSbtPlugin("org.scoverage"  % "sbt-scoverage"          % "2.0.6")
addSbtPlugin("ch.epfl.scala"  % "sbt-bloop"              % "1.5.6-61-e5171d3c")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph"   % "0.10.0-RC1")
