name: CI

on: [push]

jobs:

  scala3:

    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v7
    - name: Setup JDK
      uses: actions/setup-java@v5
      with:
        distribution: 'zulu'
        java-version: '25'
        cache: sbt
    - uses: sbt/setup-sbt@v1
    - name: compile main
      run: sbt -v --client compile
    - name: compile unit tests
      run: sbt -v --client Test/compile
    - name: tests
      run: sbt -v --client test
    - name: formatting
      run: sbt -v --client scalafmtCheckAll
    - name: assembly
      run: sbt -v --client assembly
    - name: coverage
      run: sbt -v --client xcoverage
