name: CI

on: [push]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  scala3:

    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v7
    - name: Setup JDK
      uses: ./.github/actions/setup-jdk
      with:
        cache: sbt
    - uses: sbt/setup-sbt@v1
    - name: compile main
      run: sbt -v --client compile
    - name: compile unit tests
      run: sbt -v --client Test/compile
    - name: tests
      run: sbt -v --client test
    - name: formatting
      run: sbt -v --client scalafmtCheckAll
    - name: assembly
      run: sbt -v --client assembly
    - name: coverage
      run: sbt -v --client xcoverage

  mill:

    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v7
    - name: Setup JDK
      uses: ./.github/actions/setup-jdk
    - name: compile main
      run: ./mill __.compile
    - name: compile unit tests
      run: ./mill __.test.compile + pills.zioTest.compile
    - name: tests
      run: ./mill pills.test + pills.zioTest + pills-int.test
    - name: formatting
      run: ./mill mill.scalalib.scalafmt/checkFormatAll
    - name: assembly
      run: ./mill pills.assembly
    - name: coverage
      run: ./mill pills.scoverage.xmlReport + pills.scoverage.htmlReport
