name: CI

on: [push]

jobs:

  scala3:

    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v5
    - name: Setup JDK
      uses: actions/setup-java@v5
      with:
        distribution: 'zulu'
        java-version: '21'
        cache: sbt
    - uses: sbt/setup-sbt@v1
    - name: compile main
      run: sbt -v --client compile 
      working-directory: ${{env.WORK_DIR}}
    - name: compile unit tests
      run: sbt -v --client Test/compile
      working-directory: ${{env.WORK_DIR}}
    - name: tests
      run: sbt -v --client test
      working-directory: ${{env.WORK_DIR}}
    - name: assembly
      run: sbt -v --client assembly
      working-directory: ${{env.WORK_DIR}}
