name: CI

on: [push]

jobs:

  scala3:

    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'
    - name: Cache scala dependencies
      uses: coursier/cache-action@v6
    - name: compile main
      run: sbt -v --client compile 
      working-directory: ${{env.WORK_DIR}}
    - name: compile unit tests
      run: sbt -v --client Test/compile
      working-directory: ${{env.WORK_DIR}}
    - name: tests
      run: sbt -v --client test
      working-directory: ${{env.WORK_DIR}}
    - name: assembly
      run: sbt -v --client assembly
      working-directory: ${{env.WORK_DIR}}
